// react/react-echarts.jsx
import React, {useEffect, useRef} from 'react'
import echarts from 'echarts'

export function ReactEcharts(props) {
  const {option, loading} = props
  const container = useRef(null)
  const chart = useRef(null)

  useEffect(() => {
    const width = document.documentElement.clientWidth
    const c = container.current
    console.log(c)
    c.style.width = `${width - 20}px`
    c.style.height = `${(width - 20) * 1.2}px`
    chart.current = echarts.init(c, 'dark')

  }, []) // [] - mounted on first time

  useEffect(() => {
    chart.current.setOption(option)
  }, [option]) // when option change 类似 vue 的 watch

  useEffect(() => {
    if (loading) chart.current.showLoading()
    else chart.current.hideLoading()
  }, [loading])
  return (
    <div ref={container}/>
  )
}

// vue/vue-echarts.vue
<template>
  <div ref="container"></div>
</template>


<script>
  import echarts from 'echarts'

  export default {
    props: ['option', 'loading'],
    mounted() {
      const width = document.documentElement.clientWidth
      const c = this.$refs.container
      console.log(c)
      c.style.width = `${width - 20}px`
      c.style.height = `${(width - 20) * 1.2}px`
      this.chart = echarts.init(c, 'dark')
      this.chart.setOption(this.option)
    },
    watch: {
      option() {
        this.chart.setOption(this.option)
      },
      loading() {
        if (this.loading) {
          this.chart.showLoading()
        } else {
          this.chart.hideLoading()
        }
      }
    }
  }
</script>
